added test step to github workflow

diff --git a/.github/workflows/deploy-gh-pages.yml b/.github/workflows/deploy-gh-pages.yml
--- a/.github/workflows/deploy-gh-pages.yml
+++ b/.github/workflows/deploy-gh-pages.yml
@@ -3,53 +3,63 @@ on:
   push:
     branches:
       - main
+  pull_request:
+    branches:
+      - main
   workflow_dispatch:
+
 permissions:
   contents: read
   pages: write
   id-token: write
+
 concurrency:
   group: 'pages'
   cancel-in-progress: false
+
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
-      - name: Detect package manager
-        id: detect-package-manager
-        run: |
-          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=yarn" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine package manager"
-            exit 1
-          fi
-        #   setup Node.js environment
+      #   - name: Detect package manager
+      #     id: detect-package-manager
+      #     run: |
+      #       if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+      #         echo "manager=yarn" >> $GITHUB_OUTPUT
+      #         echo "command=install" >> $GITHUB_OUTPUT
+      #         echo "runner=yarn" >> $GITHUB_OUTPUT
+      #         exit 0
+      #       elif [ -f "${{ github.workspace }}/package.json" ]; then
+      #         echo "manager=npm" >> $GITHUB_OUTPUT
+      #         echo "command=ci" >> $GITHUB_OUTPUT
+      #         echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+      #         exit 0
+      #       else
+      #         echo "Unable to determine package manager"
+      #         exit 1
+      #       fi
+      #   setup Node.js environment
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
           node-version: '18'
           cache: npm
       - name: Install dependencies
-        run: npm i
+        run: npm ci
       - name: Build project
         run: npm run build
+      - name: Run tests
+        run: npm run test
       - name: Upload artifact
         #   may need to update this action in the future https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
         uses: actions/upload-pages-artifact@v2
         with:
+          # upload dist directory's content
           path: ./dist
-  # Deployment job
+
+          # Deployment job
   deploy:
     environment:
       name: github-pages
